config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  get 'manage_aids/mpeople'

  get 'items/get_item'
  get 'items/get_sub'
  get 'items/close_new_modal'
  get 'items/get_pdf'
  

  get 'home/search'
  get 'home/update_subcategories'
  get 'home/hierarchy'
  get 'home/get_tag_names'

  get 'categories/get_category'
  get 'categories/close_new_modal'
  get 'categories/get_pdf'

  get 'tags/get_tag'
  get 'tags/close_new_modal'
  get 'tags/get_pdf'

  get 'people/get_person'
  get 'people/close_new_modal'
  get 'people/get_pdf'
  post 'people/reset_pass'

  get 'services/get_service'
  get 'services/close_new_modal'
  get 'services/get_pdf'

  get 'locations/get_location'
  get 'locations/close_new_modal'
  get 'locations/get_pdf'

  get 'roles/get_rolpeople'
  get 'roles/close_new_modal'

  get 'check_outs/release'
  get 'check_outs/check_item_in'

  post 'users/ureserve'
  post 'users/urequest'
  get 'users/requests'
  get 'users/cancel_check_out'
  get 'users/check_outs'

  get 'signup'  => 'users#new' 
  resources :users

  resources :home
  resources :categories
  resources :check_ins
  resources :check_outs
  resources :items
  resources :locations
  resources :people
  resources :requests
  resources :roles
  resources :services
  resources :sub_categories
  resources :tags

end

app/models/person.rb
class Person < ActiveRecord::Base

	validates :nationalid, length: { is: 14 }, uniqueness: true, presence: true
	validates :first_name, format: { with: /[\p{L}]{2,20}/, message: "not valid name" }, presence: true
	validates :middle_name, format: { with: /[\p{L}]{2,20}/, message: "not valid name" }, presence: true
	validates :last_name, format: { with: /[\p{L}]{2,20}/, message: "not valid name" }, presence: true
	validates :phone_number, presence: true
	validates :mobile_number1, format: { with: /(\+\d{1,3}[- ]?)?\d{11}/, message: "not valid MobNumber" }, presence: true
	validates :mobile_number2, format: { with: /(\+\d{1,3}[- ]?)?\d{11}/, message: "not valid MobNumber" }, allow_blank: true
	validates :addressA, presence: true
	validates :addressB, presence: true
	validates :addressC, presence: true
	validates :role_id, presence: true

	validate :valid_national_id

	belongs_to :role
	has_and_belongs_to_many :services
	has_many :check_outs, dependent: :destroy
	has_many :items ,through: :check_outs
	has_many :check_ins
	has_many :requests
	has_one :user

	def get_full_address
		adr = "#{addressC} #{addressB} #{addressA}"
		adr = addressD + adr unless addressD == nil
	end

	def get_full_name
		name = "#{first_name} #{middle_name} #{last_name}"
	end

	def get_all_contacts
		contacts = "Home: #{phone_number}\n"
		contacts += "Mobile: #{mobile_number1}"
		contacts += "\nMobile: #{mobile_number2}" unless mobile_number2 == nil || mobile_number2 == ""
		contacts
	end

private

	def get_birth_date

	  nationalid = self.nationalid
      year = (nationalid[0].to_i * 100) + 1700 + nationalid[1,2].to_i
      month = nationalid[3,2].to_i
      day = nationalid[5,2].to_i
      
      begin
      	self.birth_date = Date.new(year, month, day)
      rescue ArgumentError
      	false
      end

    end

    def valid_national_id
    	errors.add("National Id", "is invalid.") unless get_birth_date
    end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?
  before_filter :set_services
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index

    @people = if params[:sort] == nil
      Person.page(params[:page]).per_page(10)
    else
      if params[:sort] != "role.name"
        Person.order(params[:sort] + ' ' + params[:direction]).page(params[:page]).per_page(10)
      else
        Person.joins(:role).order('roles.name ' + params[:direction]).page(params[:page]).per_page(10)
      end
    end

    @nperson = Person.new

    @allservices = Service.all

  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  def update

    @str = nil
    @alert = nil
    @perid = @person.id

    if @person.update(person_params)
      @str = 'Servant was successfully updated'
      @alert = 'panel-success'
    else
      @str = @person.errors.full_messages
      @alert = 'panel-danger'
      @person = nil
    end
  end

  def create
    @person = Person.new(person_params)

    @str = nil
    @alert = nil

    if @person.save

      user = User.new
      user.person = @person
      user.username = @person.first_name.downcase + '.' + @person.middle_name.downcase + '.' + @person.last_name.downcase
      user.password = user.password_confirmation = @person.first_name.downcase + '.' + @person.middle_name.downcase + '777'
      user.email = user.username + '@stmarychurch.com'
      user.save

      @str = 'Servant was successfully created'
      @alert = 'panel-success'
    else
      @str = @person.errors.full_messages
      @alert = 'panel-danger'
      @person = nil
    end

  end

  def get_person

    search_natid = params[:searchNatID]
    search_mob = params[:searchMob]
    search_namef = params[:searchFirst]
    search_namem = params[:searchMidd]
    search_namel = params[:searchLast]

    @cur_person = Person
    
    unless (search_natid == nil || search_natid == "")
      @cur_person =  @cur_person.find_by(nationalid: search_natid) 
    end
     
    unless (search_namef == nil || search_namef == "")
      @cur_person =  @cur_person.where("lower(first_name) = ?", search_namef.downcase)
    end

    unless (search_namem == nil || search_namem == "")
      @cur_person =  @cur_person.where("lower(middle_name) = ?", search_namem.downcase)
    end

    unless (search_namel == nil || search_namel == "")
      @cur_person =  @cur_person.where("lower(last_name) = ?", search_namel.downcase)
    end

    unless (search_mob == nil || search_mob == "")
      @cur_person =  @cur_person.where("mobile_number1 = ? OR mobile_number2 = ?", search_mob, search_mob)
    end

    if(@cur_person == Person || @cur_person.count > 1)
      @cur_person = nil 
    else
      @cur_person = @cur_person.first
    end 


    @checkOuts = nil
    @lateCheckOuts = nil
    @topServants = nil

    unless @cur_person == nil
      
      @checkOuts = CheckOut.where(person: @cur_person)

      @lateCheckOuts = @checkOuts.where("deadline_date < ?",Time.zone.now)
      @lateCheckIns = CheckIn.where("person_id = ? AND on_deadline = ?", @cur_person.id, false)
      
      @topServants =  Person.select("items.id, items.name, items.description, items.condition, items.category_id, items.sub_category_id
                        , count(check_ins.id) AS check_ins_count")
                        .joins(people: :check_ins).where(check_ins: {person: @cur_person}).group("items.id")
                        .order("check_ins_count DESC").limit(10)
    end
    
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.user.destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reset_pass

    id = params[:per_id]
    p = Person.find(id)
    u = p.user
    u.password = u.password_confirmation = p.first_name.downcase + '.' + p.middle_name.downcase + '777'
    u.save
    
  end

  def close_new_modal
    @nperson = Person.new
  end

  def get_pdf
    allPeople = Person.all

    pdf = PeoplePdf.new(allPeople, view_context)
    send_data pdf.render, filename: 
    "Servants_List_#{Time.now.to_i}.pdf",
    type: "application/pdf"
    #disposition: inline #open in browser
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:nationalid, :first_name, :middle_name, :last_name, :addressA, :addressB, :addressC, :addressD, :phone_number, :mobile_number1, :mobile_number2, :role_id, service_ids: [])
    end

    def set_services
      @services = Service.all
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<div class="modal fade" id="<%=formid%>" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close create-form-close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">New Servant!</h4>
        </div>


<%= form_for(nperson, html: { multipart: true}, remote: true) do |f| %>

        <div class="modal-body">

          <div class="field">
            <%= f.label :nationalid, 'National Id' %>
            <%= f.text_field :nationalid , class: "btn-block"%>
          </div>

          <br>

          <div class="field">
            <%= f.label :first_name, 'First Name' %>
            <%= f.text_field :first_name, class: "btn-block" %>
          </div>

          <br>

          <div class="field">
            <%= f.label :middle_name, 'Middle Name' %>
            <%= f.text_field :middle_name, class: "btn-block" %>
          </div>

          <br>

          <div class="field">
            <%= f.label :last_name, 'Last Name' %>
            <%= f.text_field :last_name, class: "btn-block" %>
          </div>

          <br>

          <div class="field">
            <%= f.label :addressA , 'Address A'%>
            <%= f.text_field :addressA%>
          </div>

          <div class="field">
            <%= f.label :addressB , 'Address B'%>
            <%= f.text_field :addressB%>
          </div>

          <div class="field">
            <%= f.label :addressC , 'Address C'%>
            <%= f.text_field :addressC%>
          </div>

          <div class="field">
            <%= f.label :addressD , 'Address D'%>
            <%= f.text_field :addressD%>
          </div>

          <br>

          <div class="field">
            <%= f.label :phone_number %>
            <%= f.text_field :phone_number, class: "btn-block" %>
          </div>

          <div class="field">
            <%= f.label :mobile_number1 %>
            <%= f.text_field :mobile_number1, class: "btn-block" %>
          </div>

          <div class="field">
            <%= f.label :mobile_number2 %>
            <%= f.text_field :mobile_number2, class: "btn-block" %>
          </div>

          <br>

          <div class="field">
            <%= label_tag "Services" %>
            <br>
            <%= f.collection_select :service_ids, @services, :id, :serv_name, {}, {:multiple => true, class: "input-lg"} %>
          </div>

          <br>

          <% if current_user.person.role.name != "SuperAdmin" && nperson.role != nil && (nperson.role.name == "Admin" || nperson.role.name == "SuperAdmin") %>

          <% else%>

            <div class="field">
              <% roleCol = Role.all %>
              <% roleCol = roleCol.where("name != ? AND name != ?", "Admin", "SuperAdmin") unless current_user.person.role.name == "SuperAdmin" %>
              <%= f.label :role_id %><br>
              <%= f.collection_select(:role_id, roleCol, :id, :name) %>
            </div>

          <% end %>

          <br>    

        </div>

        <div id="notice-location-form<%= ('-edit' + nperson.id.to_s) unless newform  %>">
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default create-form-close" data-dismiss="modal" >Close</button>
          <%= f.submit(class: "btn btn-primary") %>
        </div>

<% end %>

</div>
    </div>
  </div>

app/views/people/_list_table_people.html.erb
<div id="create-form" linkto="<%=people_close_new_modal_path%>">

  
  <div class="btn-group pull-right">

    <%= link_to "Download Servants List", people_get_pdf_path, :class => "btn btn-default" %>
    <button class="btn btn-primary" data-toggle="modal" data-target="#person-form">Add New Servant</button>
    
  </div>

  <%= render partial: 'people/form' , locals: {nperson: nperson, formid: "person-form", newform: true} %>

</div>

<br><br>

<div>
        <strong>Sort By: </strong>
        <div class="btn-group">
          <span class="btn btn-default" ><%= sortable 'addressA','Address A', people_path %></span>
          <span class="btn btn-default" ><%= sortable 'addressB','Address B', people_path %></span> 
          <span class="btn btn-default" ><%= sortable 'addressC','Address C', people_path %></span> 
          <span class="btn btn-default" ><%= sortable 'addressD','Address D', people_path %></span>
        </div>
        <div class="btn-group">
          <span class="btn btn-default" ><%= sortable 'first_name','First Name', people_path %></span> 
          <span class="btn btn-default" ><%= sortable 'middle_name','Middle Name', people_path %></span>
          <span class="btn btn-default" ><%= sortable 'last_name','Last Name', people_path %></span> 
        </div>
        <div class="btn-group">
          <span class="btn btn-default" ><%= sortable 'mobile_number1','Mobile Number', people_path %></span>
          <span class="btn btn-default" ><%= sortable 'mobile_number2','Mobile Number2', people_path %></span>
          <span class="btn btn-default" ><%= sortable 'phone_number','Phone Number', people_path %></span> 
        </div>
      </div>
<br>

<div class="table-responsive">
  <table class="table table-hover table-condensed">
    <thead>

      <tr>
        <th><%= sortable 'nationalid','National ID', people_path %></th>
        <th>Full Name</th>
        <th><%= sortable 'birth_date','Birth Date', people_path %></th>
        <th>Address</th>
        <th>Contacts</th>
        <th><%= sortable 'role.name','Role', people_path %></th>
        
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody id="mytable">
      <% people.each do |person| %>
        <%= render partial: 'people/record' , locals: {person: person} %>
      <% end %>
    </tbody>
  </table>
  <br>

  <%= will_paginate people, renderer: BootstrapPagination::Rails %>
  <br>
</div>

app/views/people/_mperson.html.erb
<% unless person == nil %>

	<div class="thumbnail">
			<div class="caption">

				<h3><%= person.get_full_name %></h3>
				<br>

				<h3><%= person.nationalid %></h3>
				<br>

				<h3><%= person.birth_date %></h3>
				<br>

				<h3><%= person.get_full_address %></h3>
				<br>

				<h3>
					Phone: <%= person.phone_number %>
					<br>
					<br>
					Mobile: <%= person.mobile_number1 %>

					<% unless person.mobile_number2 == "" || person.mobile_number2 == nil %>
					<br>
					<br>
						Mobile2: <%= person.mobile_number2 %>
					<% else %>
					<% end %>
				</h3>
				<br>

				<h3><%= person.role.name %></h3>
				<br>				        				        			        	
			</div>

			<!-- TODO checkins, checkouts, topitems, late checkouts, late checkins -->
			<% releasedChecks = @checkOuts.where(released: false) %>
			<% unless releasedChecks.blank? %>
			<div class="caption">
				<strong>Reserved</strong>
				<div class="table-responsive">
				    <table class="table table-hover table-condensed">
					    <thead>
					      <tr>
					      	<th>ID</th>
					      	<th>Created at</th>
					      	<th>Check Out Date</th>
					      	<th>Item ID</th>
					      	<th>Location</th>
					      	<th colspan="1"></th>
					      </tr>
					    </thead>
					    <tbody>
							<% releasedChecks.each do |checkout| %>
								<%= render partial: "check_outs/release_check", locals: {checkout: checkout} %>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
			<% end %>

			<% checkOuts = @checkOuts.where(released: true) %>
			<% #unless checkOuts.blank? %>
			<div class="caption">
				<strong>Checked Out</strong>
				<div class="table-responsive">
				    <table class="table table-hover table-condensed" id="out-items">
					    <thead>
					      <tr>
					      	<th>ID</th>
					      	<th>Created at</th>
					      	<th>Check Out Date</th>
					      	<th>Deadline Date</th>
					      	<th>Item ID</th>
					      </tr>
					    </thead>
					    <tbody>
							<% checkOuts.each do |checkout| %>
								<%= render partial: "check_outs/checked_out", locals: {checkout: checkout} %>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
			<% #end %>

			<% unless @lateCheckIns.blank? %>
			<div class="caption">
				<strong>Late Check Ins</strong>
				<div class="table-responsive">
				    <table class="table table-hover table-condensed">
					    <thead>
					      <tr>
					      	<th>ID</th>
					      	<th>Created at</th>
					      	<th>Item ID</th>
					      </tr>
					    </thead>
					    <tbody>
							<% @lateCheckIns.each do |checkin| %>
								<tr>
							      	<td><%= checkin.id %></td>
							      	<td><%= checkin.created_at.to_datetime.strftime("%a, %Y-%m-%d, %l:%M %p") %></td>
							      	<td><%= checkin.item.id %></td>
						        </tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
			<% end %>

			<% unless @topItems.blank? %>
			<div class="caption">
				<strong>Top Items</strong>
				<div class="table-responsive">
				    <table class="table table-hover table-condensed">
					    <thead>
					      <tr>
					      	<th>ID</th>
					      	<th>Frequency</th>
					      	<th>Description</th>
					      	<th>Category</th>
					      	<th>SubCategory</th>
					      </tr>
					    </thead>
					    <tbody>
							<% @topItems.each do |item| %>
								<tr>
							      	<td><%= item.id %></td>
							      	<td><%= item.check_ins_count %></td>
							      	<td><%= item.description %></td>
							      	<td>
							      		<%= Category.find(item.category_id).name %>
							      	</td>
							      	<td>
							      		<% unless item.sub_category_id == nil %>
							      			<%= SubCategory.find(item.sub_category_id).name %>
							      		<% else %>
							      		<% end %>
							      	</td>
						        </tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
			<% end %>

			<% if current_user.person.role.name == "SuperAdmin" %>
				<div>
					<%= form_tag(people_reset_pass_path(per_id: person.id), remote: true) do %>
						<%= submit_tag("Reset Password",class: "btn btn-danger btn-block") %>
					<% end %>
				</div>
			<% end %>
	</div>
	
<% end %>

app/views/people/_record.html.erb
<tr id="record<%=person.id%>">

  <td><%= person.nationalid %></td>

  <td><%=person.get_full_name%></td>

  <td><%= person.birth_date %></td>

  <td><span class="label label-info glyphicon glyphicon-asterisk" data-toggle="popovert" data-content="<%=person.get_full_address%>"> </span></td>
  
  <td><span class="label label-info glyphicon glyphicon-asterisk" data-toggle="popovert" data-content="<%=simple_format(person.get_all_contacts)%>"> </span></td>

  <td><%= person.role.name %></td>

  <td>
    <%= render partial: 'people/form' , locals: {nperson: person, formid: "form-edit#{person.id}", newform: false} %>

    <button class="btn btn-info pull-right btn-block" data-toggle="modal" data-target="#form-edit<%=person.id%>">Edit</button>
  </td>

  <td>
    <% if current_user.person.role.name != "SuperAdmin" && (person.role.name == "Admin" || person.role.name == "SuperAdmin") %>
      <%= button_to 'Cannot Delete', person, remote: true, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-block disabled" %>
    <% else %>
      <%= button_to 'Delete', person, remote: true, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-block" %>
    <% end %>

  </td>
</tr>

app/views/people/close_new_modal.js.erb
$("#create-form").empty();
$("#create-form").append("<div class='btn-group pull-right'><%= escape_javascript(link_to 'Download Servants List', people_get_pdf_path, :class => 'btn btn-default') %><button class='btn btn-primary' data-toggle='modal' data-target='#person-form'>Add New Servant</button></div>");
$("#create-form").append("<%= escape_javascript(render partial: 'people/form' , locals: {nperson: @nperson, formid: 'person-form', newform: true})%>");

app/views/people/create.js.erb
$("#notice-location-form").empty();
$("#notice-location-form").append("<div class='panel' id='notice'><div class='panel-heading' id='noticeh'></div></div>"); 
 
<% if @person == nil %>

	$("#noticeh").append("<div class='panel-title'>Failed: </div><ul id='noticeb'></ul>");

	<% @str.each do |s| %>
		$("#noticeb").append("<li><%= s %></li>");
	<% end %>
	
<% else %>

	$("#mytable").prepend("<%=escape_javascript(render partial: 'people/record' , locals: {allservices: @allservices,person: @person})%>");
	$("#noticeh").append("<%= @str %>");
	//window.location.reload();

	$('[data-toggle="popovert"]').popover({
        html: true,
        trigger: 'hover'
    });

<% end %>

$("#notice").addClass("<%= @alert %>");

app/views/people/destroy.js.erb
$("#record<%=@personid%>").replaceWith("<div id='record<%=@personid%>' class='panel panel-danger'><div class='panel-heading'><div class='panel-title'>Deleting Person</div></div></div>");
$("#record<%=@personid%>").fadeOut(1000);

app/views/people/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/people/get_person.js.erb
<% unless @cur_person == nil %>
	$("#srchPersonPos").html("<%= escape_javascript(render partial: 'people/mperson', locals: { person:  @cur_person, serv: @services } ) %>"); 
<% else %>
	$("#srchPersonPos").empty(); 
	$("#srchPersonPos").append("<div class='panel panel-danger'><div class='panel-heading'><div class='panel-title'>Not Enough Criteria To Find A Unique Servant Please Enter More Information!</div></div></div>");
<% end %>

app/views/people/index.html.erb
<h1>Manage Servants</h1>

<div role="tabpanel" class="shadow-z-4" style="background-color:#ffffff;">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">

    <li role="presentation"  class="active">
      <a href="#crud" aria-controls="crud" role="tab" data-toggle="tab">Create & edit Servants</a>
    </li>

    <li role="presentation" >
      <a href="#srchitem" aria-controls="srchitem" role="tab" data-toggle="tab">Search for a Servant</a>
    </li>

    <li role="presentation">
      <a href="#topc" aria-controls="topi" role="tab" data-toggle="tab"></a>
    </li>

  </ul>

  <!-- Tab panes -->
  <div class="tab-content crud-content">

    <div role="tabpanel" class="tab-pane active" id="crud">
      <%= render partial: 'people/list_table_people' , locals: {people: @people, nperson: @nperson } %>
    </div>

    <div role="tabpanel" class="tab-pane" id="srchitem">

      <div class="form-group">

             <div class="input-group btn-group">

                <%= form_tag(people_get_person_path, method: "get", remote: true, id: "crud-srch") do %>
                    
                    <div class="btn-group btn-block">
                      <div class="btn-group btn-block">
                          <%= text_field_tag(:searchNatID, nil,class: "form-control", placeholder: "national id") %>
                      </div>
                      <div class="btn-group btn-block">
                          <%= text_field_tag(:searchMob, nil,class: "form-control", placeholder: "mobile number") %>
                      </div>
                      <div class="btn-group btn-block">
                          <%= text_field_tag(:searchFirst, nil,class: "form-control", placeholder: "first name") %>
                      </div>
                      <div class="btn-group btn-block">
                          <%= text_field_tag(:searchMidd, nil,class: "form-control", placeholder: "middle name") %>
                      </div>
                      <div class="btn-group btn-block">
                          <%= text_field_tag(:searchLast, nil,class: "form-control", placeholder: "last name") %>
                      </div>
                      
                      <div class="btn-group btn-block">             
                          <%= submit_tag("Get servant!",class: "btn btn-default")%>
                      </div>
                    
                    </div>

                <% end %>

              </div>
          </div>

      <div id="srchPersonPos">
      </div>

    </div>

    <div role="tabpanel" class="tab-pane" id="topc">
      
    </div>
    
  </div>

</div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/reset_pass.js.erb
alert("User's password was reset!");

app/views/people/update.js.erb
$("#notice-location-form-edit<%= @perid %>").empty();
$("#notice-location-form-edit<%= @perid %>").append("<div class='panel' id='notice<%= @perid %>'><div class='panel-heading' id='noticeh<%= @perid %>'></div></div>"); 
 
<% if @person == nil %>

	$("#noticeh<%= @perid %>").append("<div class='panel-title'>Failed: </div><ul id='noticeb<%= @perid %>'></ul>");

	<% @str.each do |s| %>
		$("#noticeb<%= @perid %>").append("<li><%= s %></li>");
	<% end %>

	$("#notice<%= @perid %>").addClass("<%= @alert %>");
	
<% else %>

	$("#record<%=@person.id%>").replaceWith("<%=escape_javascript(render partial: 'people/record' , locals: {person: @person})%>");
	//$("#noticeh<%= @personid %>").append("<%= @str %>");

	$('[data-toggle="popovert"]').popover({
        html: true,
        trigger: 'hover'
    });

	$("#msgmodal").replaceWith("<%=escape_javascript(render partial: 'layouts/confirm' , locals: {str: @str})%>");
	$("#mymodal").modal("show");
<% end %>