config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  get 'manage_aids/mpeople'

  get 'items/get_item'
  get 'items/get_sub'
  get 'items/close_new_modal'
  get 'items/get_pdf'
  

  get 'home/search'
  get 'home/update_subcategories'
  get 'home/hierarchy'
  get 'home/get_tag_names'

  get 'categories/get_category'
  get 'categories/close_new_modal'
  get 'categories/get_pdf'

  get 'tags/get_tag'
  get 'tags/close_new_modal'
  get 'tags/get_pdf'

  get 'people/get_person'
  get 'people/close_new_modal'
  get 'people/get_pdf'
  post 'people/reset_pass'

  get 'services/get_service'
  get 'services/close_new_modal'
  get 'services/get_pdf'

  get 'locations/get_location'
  get 'locations/close_new_modal'
  get 'locations/get_pdf'

  get 'roles/get_rolpeople'
  get 'roles/close_new_modal'

  get 'check_outs/release'
  get 'check_outs/check_item_in'

  post 'users/ureserve'
  post 'users/urequest'
  get 'users/requests'
  get 'users/cancel_check_out'
  get 'users/check_outs'

  get 'signup'  => 'users#new' 
  resources :users

  resources :home
  resources :categories
  resources :check_ins
  resources :check_outs
  resources :items
  resources :locations
  resources :people
  resources :requests
  resources :roles
  resources :services
  resources :sub_categories
  resources :tags

end

app/models/tag.rb
class Tag < ActiveRecord::Base

	validates :name, uniqueness: true, presence: true
	

	has_and_belongs_to_many :items


	def self.counts
  		self.select("name, count(items_tags.tag_id) as count").joins(:items_tags).group("items_tags.tag_id")
	end
	
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :is_admin?

  def index

    @topTags ||= Tag.select(:name, "count(check_ins.id) AS checkins_count")
    .joins(items: :check_ins).group("tags.id").order("checkins_count DESC").limit(10)

    @tags = Tag.all.page(params[:page]).per_page(10).order(:name)

    @ntag = Tag.new

  end


  def show
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    @str = nil
    @alert = nil

    if @tag.save
      @str = 'Tag was successfully created'
      @alert = 'panel-success'
    else
      @str = @tag.errors.full_messages
      @alert = 'panel-danger'
      @tag = nil
    end

  end


  def update
    @str = nil
    @alert = nil
    @tagid = @tag.id

    if @tag.update(tag_params)
      @str = 'Tag was successfully updated'
      @alert = 'panel-success'
    else
      @str = @tag.errors.full_messages
      @alert = 'panel-danger'
      @tag = nil
    end
  end

  def close_new_modal
    @ntag = Tag.new
  end


  def destroy
    @tagid = params[:id]
    Tag.destroy(@tagid)
  end

  def get_tag
    tag_name = params[:tagName]

    @cur_tag = nil
    @services = nil
    
    if tag_name
      @cur_tag = Tag.where(name: tag_name).first
      @services = Service.select([:id,:name,:sub_name,"count(check_ins.id) AS checkins"])
      .joins(people: :check_ins).where(check_ins: {item_id: @cur_tag.items}).group("services.id").order('count(check_ins.id) DESC')
    end
  end

  def get_pdf
    alltags = Tag.all

    pdf = TagsPdf.new(alltags, view_context)
    send_data pdf.render, filename: 
    "Tags_List_#{Time.now.to_i}.pdf",
    type: "application/pdf"
    #disposition: inline #open in browser

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class="modal fade" id="<%=formid%>" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close create-form-close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">New Tag!</h4>
        </div>


<%= form_for(ntag, html: { multipart: true}, remote: true) do |f| %>

        <div class="modal-body">

          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>
          <br>     

        </div>

        <div id="notice-location-form<%= ('-edit' + ntag.id.to_s) unless newform  %>">
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default create-form-close" data-dismiss="modal" >Close</button>
          <%= f.submit(class: "btn btn-primary") %>
        </div>

<% end %>

</div>
    </div>
  </div>

app/views/tags/_list_table_tags.html.erb
<div id="create-form" linkto="<%=tags_close_new_modal_path%>">

  
  <div class="btn-group pull-right">

    <%= link_to "Download Tags List", tags_get_pdf_path, :class => "btn btn-default" %>
    <button class="btn btn-primary" data-toggle="modal" data-target="#tag-form">Add New Tag</button>
    
  </div>

  <%= render partial: 'tags/form' , locals: {ntag: ntag, formid: "tag-form", newform: true} %>

</div>

<br><br>

<div class="table-responsive btn-block">
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody id="mytable">
      <% tags.each do |tag| %>
        <%= render partial: 'tags/record' , locals: {tag: tag} %>
      <% end %>
    </tbody>
  </table>
  <br>

  <%= will_paginate tags, renderer: BootstrapPagination::Rails %>
  <br>
</div>

app/views/tags/_list_top_tags.html.erb
<% unless tags == nil %>

	<% tags.in_groups_of(4,false).each do |group| %>
		<div class="row">
			<% group.each do |tag| %>
				<div class="col-sm-6 col-md-3">
				    <div class="thumbnail">
				    	<span class="badge"><%= tag.checkins_count %> Check ins</span> 
				      <div class="caption">
				        <h3><%= tag.name %></h3>
				      </div>
				    </div>
			  	</div>
		  <% end %>
		</div>
	<% end %>
<% else %>

emptyyyyyy

<% end %>

app/views/tags/_mtag.html.erb
<% unless tag == nil %>

	<div class="thumbnail">
			<div class="caption">
					        <h3><%= tag.name %></h3>
					        			        	
				<% unless serv.empty? %>
					<div>
						<strong>Services:</strong>
						<br>
						<ul class="list-group">
							<% serv.each do |s| %>
							  <li class="list-group-item"><%= s.name %>  <%= s.sub_name %>  <span class="badge"><%= s.checkins %> Points</span></li>
						 	<% end %>
						</ul>
					</div>
				<% end %>
			</div>
	</div>
	
<% end %>

app/views/tags/_record.html.erb
<tr id="record<%=tag.id%>">
  <td><%= tag.name %></td>

  <td>
    <%= render partial: 'tags/form' , locals: {ntag: tag, formid: "form-edit#{tag.id}", newform: false} %>
    <button class="btn btn-info pull-right btn-block" data-toggle="modal" data-target="#form-edit<%=tag.id%>">Edit</button>
  </td>

  <td>

    <%= button_to 'Delete', tag, remote: true, method: :delete, data: {confirm: "this tag is linked to #{tag.items.count} items! Are you sure?"}, class: "btn btn-danger btn-block" %>

  </td>
</tr>

app/views/tags/close_new_modal.js.erb
$("#create-form").empty();
$("#create-form").append("<div class='btn-group pull-right'><%= escape_javascript(link_to 'Download Tags List', tags_get_pdf_path, :class => 'btn btn-default') %><button class='btn btn-primary' data-toggle='modal' data-target='#tag-form'>Add New Tag</button></div>");
$("#create-form").append("<%= escape_javascript(render partial: 'tags/form' , locals: {ntag: @ntag, formid: 'tag-form', newform: true})%>");

app/views/tags/create.js.erb
$("#notice-location-form").empty();
$("#notice-location-form").append("<div class='panel' id='notice'><div class='panel-heading' id='noticeh'></div></div>"); 
 
<% if @tag == nil %>

	$("#noticeh").append("<div class='panel-title'>Failed: </div><ul id='noticeb'></ul>");

	<% @str.each do |s| %>
		$("#noticeb").append("<li><%= s %></li>");
	<% end %>
	
<% else %>

	$("#mytable").prepend("<%=escape_javascript(render partial: 'tags/record' , locals: {tag: @tag})%>");
	$("#noticeh").append("<%= @str %>");
	//window.location.reload();

<% end %>

$("#notice").addClass("<%= @alert %>");

app/views/tags/destroy.js.erb
$("#record<%=@tagid%>").replaceWith("<div id='record<%=@tagid%>' class='panel panel-danger'><div class='panel-heading'><div class='panel-title'>Deleting Tag</div></div></div>");
$("#record<%=@tagid%>").fadeOut(1000);

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/get_tag.js.erb
<% unless @cur_tag == nil %>
	$("#srchTagPos").html("<%= escape_javascript(render partial: 'tags/mtag', locals: { tag:  @cur_tag, serv: @services } ) %>"); 
<% else %>
	$("#srchTagPos").empty(); 
<% end %>

app/views/tags/index.html.erb
<h1>Manage Tags</h1>

<div role="tabpanel" class="shadow-z-4" style="background-color:#ffffff;">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">

    <li role="presentation"  class="active">
      <a href="#crud" aria-controls="crud" role="tab" data-toggle="tab">Create & edit Tags</a>
    </li>

    <li role="presentation" >
      <a href="#srchitem" aria-controls="srchitem" role="tab" data-toggle="tab">Search for a Tag</a>
    </li>

    <li role="presentation">
      <a href="#topc" aria-controls="topi" role="tab" data-toggle="tab">Top Tags</a>
    </li>

  </ul>

  <!-- Tab panes -->
  <div class="tab-content crud-content">

    <div role="tabpanel" class="tab-pane active" id="crud">
      <%= render partial: 'tags/list_table_tags' , locals: { tags: @tags, ntag: @ntag } %>
    </div>

    <div role="tabpanel" class="tab-pane" id="srchitem">

      <div class="form-group">

             <div class="input-group btn-group">

                <%= form_tag(tags_get_tag_path, method: "get", remote: true, id: "crud-srch") do %>
                    
                    <div class="btn-group">
                      <div class="btn-group">
                          <%= text_field_tag(:tagName, nil,class: "form-control", placeholder: "tag name") %>
                      </div>
                      
                      <div class="btn-group">             
                          <%= submit_tag("Get tag!",class: "btn btn-default")%>
                      </div>
                    
                    </div>

                <% end %>

              </div>
          </div>

      <div id="srchTagPos">
      </div>

    </div>

    <div role="tabpanel" class="tab-pane" id="topc">
      <%= render partial: 'tags/list_top_tags' , locals: { tags: @topTags } %>
    </div>
    
  </div>

</div>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/tags/update.js.erb
$("#notice-location-form-edit<%= @tagid %>").empty();
$("#notice-location-form-edit<%= @tagid %>").append("<div class='panel' id='notice<%= @tagid %>'><div class='panel-heading' id='noticeh<%= @tagid %>'></div></div>"); 
 
<% if @tag == nil %>

	$("#noticeh<%= @tagid %>").append("<div class='panel-title'>Failed: </div><ul id='noticeb<%= @tagid %>'></ul>");

	<% @str.each do |s| %>
		$("#noticeb<%= @tagid %>").append("<li><%= s %></li>");
	<% end %>

	$("#notice<%= @tagid %>").addClass("<%= @alert %>");
	
<% else %>

	$("#record<%=@tag.id%>").replaceWith("<%=escape_javascript(render partial: 'tags/record' , locals: {tag: @tag})%>");
	//$("#noticeh<%= @tagid %>").append("<%= @str %>");
	
	$("#msgmodal").replaceWith("<%=escape_javascript(render partial: 'layouts/confirm' , locals: {str: @str})%>");
	$("#mymodal").modal("show");

<% end %>