config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  get 'manage_aids/mpeople'

  get 'items/get_item'
  get 'items/get_sub'
  get 'items/close_new_modal'
  get 'items/get_pdf'
  

  get 'home/search'
  get 'home/update_subcategories'
  get 'home/hierarchy'
  get 'home/get_tag_names'

  get 'categories/get_category'
  get 'categories/close_new_modal'
  get 'categories/get_pdf'

  get 'tags/get_tag'
  get 'tags/close_new_modal'
  get 'tags/get_pdf'

  get 'people/get_person'
  get 'people/close_new_modal'
  get 'people/get_pdf'
  post 'people/reset_pass'

  get 'services/get_service'
  get 'services/close_new_modal'
  get 'services/get_pdf'

  get 'locations/get_location'
  get 'locations/close_new_modal'
  get 'locations/get_pdf'

  get 'roles/get_rolpeople'
  get 'roles/close_new_modal'

  get 'check_outs/release'
  get 'check_outs/check_item_in'

  post 'users/ureserve'
  post 'users/urequest'
  get 'users/requests'
  get 'users/cancel_check_out'
  get 'users/check_outs'

  get 'signup'  => 'users#new' 
  resources :users

  resources :home
  resources :categories
  resources :check_ins
  resources :check_outs
  resources :items
  resources :locations
  resources :people
  resources :requests
  resources :roles
  resources :services
  resources :sub_categories
  resources :tags

end

app/models/item.rb
class Item < ActiveRecord::Base

	mount_uploader :photo , PhotoUploader

	validates :name, format: { with: /[\p{L}]{2,25}/, message: "not valid name" }, presence: true
	validates :condition, inclusion: { in: %w(OK MAINTENANCE LOST), message: "${value} is not a valid condition, conditions are either OK , MAINTENANCE or LOST " }, presence: true
	validates :category_id, presence: true
	validates :location_id, presence: true
	validates :photo, presence: true

	belongs_to :category
	belongs_to :sub_category
	belongs_to :location
	has_one :check_out, dependent: :destroy
	has_one :person ,through: :check_out
	has_many :check_ins
	has_many :people ,through: :check_ins
	has_and_belongs_to_many :tags
	has_many :requests

	def self.for_tag(tag_name)
  		where("id IN (#{ItemsTag.item_ids_for_tag(tag_name).to_sql})")
	end

 
		#	@file_data = file_data if endfile_data.original_filename.split('.').last.downcase == 'png'
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :set_tags

  #autocomplete :tag, :name, full: true

  def index

    @topItems ||=  Item.select("items.id, items.name, items.description, items.condition, items.category_id, items.sub_category_id
      , items.photo , count(check_ins.id) AS checkins_count").
    joins(:check_ins).group("items.id").
    order("checkins_count DESC").limit(10)

    @items = if params[:sort] == nil
      Item.page(params[:page]).per_page(10)
    else
      Item.includes(:category).order(params[:sort] + ' ' + params[:direction]).page(params[:page]).per_page(10)
    end

    @nitem = Item.new

  end

  def update

    @str = nil
    @alert = nil
    @itmid = @item.id

    if @item.update(item_params)
      @str = 'Item was successfully updated'
      @alert = 'panel-success'
    else
      @str = @item.errors.full_messages
      @alert = 'panel-danger'
      @item = nil
    end
  end

  def create
    @item = Item.new(item_params)

    @str = nil
    @alert = nil

    if @item.save
      @str = 'Item was successfully created'
      @alert = 'panel-success'
    else
      @str = @item.errors.full_messages
      @alert = 'panel-danger'
      @item = nil
    end

  end

  def get_item
    itemID = params[:itemID].to_i

    @cur_item = nil
    @services = nil
    
    if itemID > 0
      @cur_item = Item.where(id: itemID).first
      @services = Service.select([:id,:name,:sub_name,"count(check_ins.id) AS checkins"])
      .joins(people: :check_ins).where(check_ins: {item_id: itemID}).group("services.id")
    end
  end

  def get_sub

    @subs = (Category.find(params[:cat_id].to_i)).sub_categories
    @tagid = params[:tagid]

  end


  def show
  end

  def new
    @item = Item.new
  end

  def destroy

    @itmid = params[:id]
    Item.destroy(@itmid)

  end

  def close_new_modal
    @nitem = Item.new
  end

  def get_pdf
    allItems = Item.all

    pdf = ItemsPdf.new(allItems, view_context)
    send_data pdf.render, filename: 
    "Items_List_#{Time.now.to_i}.pdf",
    type: "application/pdf"
    #disposition: inline #open in browser
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:photo, :name, :description, :cost, :condition, :category_id, :sub_category_id, :location_id, :customid, tag_ids: [])
    end

    def set_tags
      @tags = Tag.all
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="modal fade" id="<%=formid%>" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close create-form-close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">New Item!</h4>
        </div>

        <% if newform %>
          <div id="notmodal"></div>
        <% end %>


<%= form_for(nitem, html: { multipart: true}, remote: true) do |f| %>

        <div class="modal-body">

          <div class="field">
            <%= f.label :photo %><br>
            <%= f.file_field :photo %>
            <%= f.hidden_field :photo_cache %>
          </div>
          <br>
          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>
          <br>
          <div class="field">
            <%= f.label :customid %><br>
            <%= f.text_field :customid %>
          </div>
          <br>
          <div class="field">
            <%= f.label :description %><br>
            <%= f.text_area :description %>
          </div>
          <br>
          <div class="field">
            <%= f.label :cost %><br>
            <%= f.number_field :cost %>
          </div>
          <br>
          <div class="field">
            <%= f.label :condition %><br>
            <%= f.select(:condition, options_for_select([["Ok","OK"],["Maintenance","MAINTENANCE"],["Lost","LOST"]],"OK")) %>
          </div>
          <br>
          
            <div id="asd<%=tagid%>" class="field" linkto="<%=items_get_sub_path%>">
              <%= f.label :category_id %><br>
              <%= f.collection_select :category_id, Category.all, :id, :name ,{prompt: true} ,
              onChange: "
                $.ajax({
                  url: $('#asd#{tagid}').attr('linkto')
                  ,data: { cat_id: $('#asd#{tagid} #item_category_id').val(), tagid: #{tagid}}
                  ,dataType: 'script'
                });
              "%>
            </div>
            <br>

            <div class="field" id="form-subcat<%=tagid%>">

              <% unless tagid == 0 %>
                <%=label_tag "Subcategory"%>
                <br>
                <%=f.collection_select(:sub_category_id , nitem.category.sub_categories,:id, :name, include_blank: 'none')%>
              <% end %>

            </div>
          <br>

          <div class="field">
            <%= label_tag "Location" %>
            <br>
            <%= f.collection_select(:location_id, Location.all, :id, :get_full_name, include_blank: 'none')%>
          </div>

          <br>
          <div class="field">
            <%= label_tag "Tags" %>
            <br>
            <%= f.collection_select :tag_ids, @tags, :id, :name, {}, {:multiple => true, class: "input-lg"} %>
          </div>

        </div>


        <div id="notice-location-form<%= ('-edit' + nitem.id.to_s) unless newform  %>">
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default create-form-close" data-dismiss="modal" >Close</button>
          <%= f.submit(class: "btn btn-primary") %>
        </div>

<% end %>

</div>
    </div>
  </div>

app/views/items/_list_table_items.html.erb
<div id="create-form" linkto="<%=items_close_new_modal_path%>">

  
  <div class="btn-group pull-right">
    <%= link_to "Download Items List", items_get_pdf_path, :class => "btn btn-default" %>
    <button class="btn btn-primary" data-toggle="modal" data-target="#item-form">Add New Item</button>
  </div>

  <%= render partial: 'items/form' , locals: {nitem: nitem, formid: "item-form", tagid: 0,newform: true} %>

</div>

<br><br>

<div class="table-responsive btn-block">
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th><%= sortable 'customid','customID', items_path %></th>
        <th><%= sortable 'id','ID', items_path %></th>
        <th><%= sortable 'name','Name', items_path %></th>
        <th>Description</th>
        <th><%= sortable 'cost','Cost', items_path %></th>
        <th><%= sortable 'condition','Condition', items_path %></th>
        <th><%= sortable 'categories.name','Category', items_path %></th>
        <th>Sub category</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody id="mytable">
      <% items.each do |item| %>
        <%= render partial: 'items/record' , locals: {item: item} %>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate items, renderer: BootstrapPagination::Rails %>

  <br>
</div>

app/views/items/_list_top_items.html.erb
<% unless items == nil %>

	<% items.in_groups_of(4,false).each do |group| %>
		<div class="row">
			<% group.each do |item| %>
				<div class="col-sm-6 col-md-3">
				    <div class="thumbnail">
				    	<span class="badge"><%= item.checkins_count %> Check ins</span> 
				      <%= image_tag item.photo_url.to_s %>
				      <div class="caption">
				        <h3><%= item.name %></h3>
				        <%= label_tag 'Description:' %>
				        <p><%= item.description %></p>
				        <p><% cat = item.category %></p>
				        <%= label_tag 'Category:' %>
				        <p><%= cat.name %></p>
				        <p>
				        	<%= label_tag 'Subcategory:' %>
				        	<p>
					        	<% unless item.sub_category == nil %>
					        	<%= item.sub_category.name %>
					        	<% end %>
				        	</p>
				        </p>
				      </div>
				    </div>
			  	</div>
		  <% end %>
		</div>
	<% end %>

<% end %>

app/views/items/_mitem.html.erb
<% unless itm == nil %>

	<div class="thumbnail">
			<%= image_tag itm.photo_url.to_s if itm.photo?%>
			<div class="caption">
					        <h3>Name: <%= itm.name %></h3>
					        <%= label_tag 'Location:' %>
					        <p><%= itm.location.get_full_name %></p>
					        <% unless itm.description == "" %>
						        <%= label_tag 'Description:' %>
						        <p><%= itm.description %></p>
						    <% else %>
						    	-<%= label_tag 'No Description available' %>-
						    <% end %>

					        <p><% cat = itm.category %></p>
					        <%= label_tag 'Category:' %>
					        <p><%= cat.name %></p>
					        <p>
					        	<%= label_tag 'Subcategory:' %>
					        	<p>
						        	<% unless itm.sub_category == nil %>
						        	<%= itm.sub_category.name %>
						        	<% end %>
					        	</p>
					        </p>
					        <p>
				        	<%= label_tag 'Tags:' %>
				        	<% itm.tags.each do |s| %>
								<span class="label label-info"><%= s.name %></span>
							<% end %>
				        	</p>
				<% unless serv.empty? %>
					<div>
						<strong>Services:</strong>
						<br>
						<ul class="list-group">
							<% serv.each do |s| %>
							  <li class="list-group-item"><%= s.name %>  <%= s.sub_name %>  <span class="badge"><%= s.checkins %> Points</span></li>
						 	<% end %>
						</ul>
					</div>
				<% end %>
			</div>
	</div>
	
<% end %>

app/views/items/_record.html.erb
<tr id="record<%=item.id%>">
  <td><span class="badge"><strong><%= item.customid %></strong></span></td>
  <td><span class="badge"><strong><%= item.id %></strong></span></td>
  <td><%= item.name %></td>
  <td><%= item.description %></td>
  <td><%= item.cost %></td>
  <td><%= item.condition %></td>
  <td><%= item.category.name %></td>
  <td><%= item.sub_category.name unless item.sub_category == nil%></td>

  <td>
    <button class="btn btn-default pull-right active btn-block" data-toggle="popover" data-img="<%= item.photo_url.to_s if item.photo?%>" data-placement="left">Show</button>
  </td>

  <td>
    <%= render partial: 'items/form' , locals: {nitem: item, formid: "form-edit#{item.id}", tagid: item.id, newform: false} %>
    <button class="btn btn-info pull-right btn-block" data-toggle="modal" data-target="#form-edit<%=item.id%>">Edit</button>
  </td>

  <td>
    <%= button_to 'Delete', item, remote: true, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-block" %>
  </td>
</tr>

app/views/items/close_new_modal.js.erb
$("#create-form").empty();
$("#create-form").append("<div class='btn-group pull-right'><%= escape_javascript(link_to 'Download Items List', items_get_pdf_path, :class => 'btn btn-default') %><button class='btn btn-primary' data-toggle='modal' data-target='#item-form'>Add New Item</button></div>");
$("#create-form").append("<%= escape_javascript(render partial: 'items/form' , locals: {nitem: @nitem, formid: 'item-form', tagid: 0, newform: true})%>");

app/views/items/create.js.erb
$("#notice-location-form").empty();
$("#notice-location-form").append("<div class='panel' id='notice'><div class='panel-heading' id='noticeh'></div></div>"); 
 
<% if @item == nil %>

	$("#noticeh").append("<div class='panel-title'>Failed: </div><ul id='noticeb'></ul>");

	<% @str.each do |s| %>
		$("#noticeb").append("<li><%= s %></li>");
	<% end %>
	
<% else %>

	$("#mytable").prepend("<%=escape_javascript(render partial: 'items/record' , locals: {item: @item})%>");
	$("#noticeh").append("<%= @str %>");
	//window.location.reload();

	$('[data-toggle="popover"]').popover({
        html: true,
        trigger: 'hover',
        content: function () {
          return '<img src="'+$(this).data('img') + '" />';
        }
      });


	$("#notmodal").replaceWith("<%=escape_javascript(render partial: 'layouts/confirm_new' , locals: {itmid: @item.id})%>");
	$("#mynotmodal").modal("show");

	$(".create-form-close").on("click",(function(){

        if( $('#notice-location-form').find('#notice').length )
        {
          $.ajax({
            url: $("#create-form").attr('linkto'),
            dataType: "script"
          });
        }

      }));

<% end %>

$("#notice").addClass("<%= @alert %>");

app/views/items/destroy.js.erb
$("#record<%=@itmid%>").replaceWith("<div id='record<%=@itmid%>' class='panel panel-danger'><div class='panel-heading'><div class='panel-title'>Deleting item with id <%=@itmid%></div></div></div>");
$("#record<%=@itmid%>").fadeOut(1000);

app/views/items/get_item.js.erb
<% unless @cur_item == nil %>
	$("#srchItemPos").html("<%= escape_javascript(render partial: 'items/mitem', locals: { itm:  @cur_item, serv: @services } ) %>"); 
<% else %>
	$("#srchItemPos").empty(); 
<% end %>

app/views/items/get_sub.js.erb
$("#form-subcat<%=@tagid%>").empty();

<% unless @subs.empty? %>

	$("#form-subcat<%=@tagid%>").html("<%=escape_javascript(label_tag "Subcategory")%><br><%=escape_javascript( 
		collection_select(:item, :sub_category_id , @subs, :id, :name, include_blank: 'none')
		 )%>");

<% end %>

app/views/items/index.html.erb
<h1>Manage Aids</h1>

<div role="tabpanel" class="crudpanel shadow-z-4" style="background-color:#ffffff;">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">

  	<li role="presentation"  class="active">
      <a href="#crud" aria-controls="crud" role="tab" data-toggle="tab">Create & edit Items</a>
    </li>

    <li role="presentation" >
    	<a href="#srchitem" aria-controls="srchitem" role="tab" data-toggle="tab">Search for an Item</a>
    </li>

    <li role="presentation">
      <a href="#topi" aria-controls="topi" role="tab" data-toggle="tab">Top Items</a>
    </li>

  </ul>

  <!-- Tab panes -->
  <div class="tab-content crud-content">

    <div role="tabpanel" class="tab-pane active" id="crud">
      <%= render partial: 'items/list_table_items' , locals: { items: @items, nitem: @nitem } %>
    </div>

    <div role="tabpanel" class="tab-pane" id="srchitem">

		<div class="form-group">

           <div class="input-group btn-group">

              <%= form_tag(items_get_item_path, method: "get", remote: true, id: "crud-srch") do %>
                  
                  <div class="btn-group">
                    <div class="btn-group">
                        <%= text_field_tag(:itemID, nil,class: "form-control", placeholder: "item id") %>
                    </div>
                    
                    <div class="btn-group">             
                        <%= submit_tag("Get item!",class: "btn btn-default")%>
                    </div>
                  
                  </div>

              <% end %>

            </div>
        </div>

		<div id="srchItemPos">
		</div>

    </div>

    <div role="tabpanel" class="tab-pane" id="topi">
      <%= render partial: 'items/list_top_items' , locals: { items: @topItems } %>
    </div>
    
  </div>

</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @item.cost %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @item.condition %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category_id %>
</p>

<p>
  <strong>Sub category:</strong>
  <%= @item.sub_category_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @item.location_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/items/update.js.erb
$("#notice-location-form-edit<%= @itmid %>").empty();
$("#notice-location-form-edit<%= @itmid %>").append("<div class='panel' id='notice<%= @itmid %>'><div class='panel-heading' id='noticeh<%= @itmid %>'></div></div>"); 
 
<% if @item == nil %>

	$("#noticeh<%= @itmid %>").append("<div class='panel-title'>Failed: </div><ul id='noticeb<%= @itmid %>'></ul>");

	<% @str.each do |s| %>
		$("#noticeb<%= @itmid %>").append("<li><%= s %></li>");
	<% end %>

	$("#notice<%= @itmid %>").addClass("<%= @alert %>");
	
<% else %>

	$("#record<%=@item.id%>").replaceWith("<%=escape_javascript(render partial: 'items/record' , locals: {item: @item})%>");
	//$("#noticeh<%= @itmid %>").append("<%= @str %>");

	 $('[data-toggle="popover"]').popover({
        html: true,
        trigger: 'hover',
        content: function () {
          return '<img src="'+$(this).data('img') + '" />';
        }
      });

	$("#msgmodal").replaceWith("<%=escape_javascript(render partial: 'layouts/confirm' , locals: {str: @str})%>");
	$("#mymodal").modal("show");

	//window.location.reload();

<% end %>