config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  get 'manage_aids/mpeople'

  get 'items/get_item'
  get 'items/get_sub'
  get 'items/close_new_modal'
  get 'items/get_pdf'
  

  get 'home/search'
  get 'home/update_subcategories'
  get 'home/hierarchy'
  get 'home/get_tag_names'

  get 'categories/get_category'
  get 'categories/close_new_modal'
  get 'categories/get_pdf'

  get 'tags/get_tag'
  get 'tags/close_new_modal'
  get 'tags/get_pdf'

  get 'people/get_person'
  get 'people/close_new_modal'
  get 'people/get_pdf'
  post 'people/reset_pass'

  get 'services/get_service'
  get 'services/close_new_modal'
  get 'services/get_pdf'

  get 'locations/get_location'
  get 'locations/close_new_modal'
  get 'locations/get_pdf'

  get 'roles/get_rolpeople'
  get 'roles/close_new_modal'

  get 'check_outs/release'
  get 'check_outs/check_item_in'

  post 'users/ureserve'
  post 'users/urequest'
  get 'users/requests'
  get 'users/cancel_check_out'
  get 'users/check_outs'

  get 'signup'  => 'users#new' 
  resources :users

  resources :home
  resources :categories
  resources :check_ins
  resources :check_outs
  resources :items
  resources :locations
  resources :people
  resources :requests
  resources :roles
  resources :services
  resources :sub_categories
  resources :tags

end

app/models/category.rb
class Category < ActiveRecord::Base

	validates :name, format: { with: /[\p{L}]{2,30}/, message: "not valid name" }, presence: true

	has_many :sub_categories, dependent: :destroy
	has_many :items
	accepts_nested_attributes_for :sub_categories,reject_if: :all_blank, allow_destroy: true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :is_admin?

  # GET /categories
  # GET /categories.json
  def index

    @topCategories ||=  Category.select(:id, :name, :description,"count(check_ins.id) AS checkins_count")
    .joins(items: :check_ins).group("categories.id").order("checkins_count DESC").limit(10)

    @categories = if params[:sort] == nil
      Category.all
    else
      Category.order(params[:sort] + ' ' + params[:direction])
    end

    @ncategory = Category.new

  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    @str = nil
    @alert = nil

    if @category.save
      @str = 'Category was successfully created'
      @alert = 'panel-success'
    else
      @str = @category.errors.full_messages
      @alert = 'panel-danger'
      @category = nil
    end

  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    @str = nil
    @alert = nil
    @catid = @category.id

    if @category.update(category_params)
      @str = 'Category was successfully updated'
      @alert = 'panel-success'
    else
      @str = @category.errors.full_messages
      @alert = 'panel-danger'
      @category = nil
    end
  end

  def close_new_modal
    @ncategory = Category.new
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @catid = params[:id]
    Category.destroy(@catid)
  end

  def get_category
    cat_name = params[:catName]

    @cur_cat = nil
    @services = nil
    
    if cat_name
      @cur_cat = Category.where(name: cat_name).first
      @services = Service.select([:id,:name,:sub_name,"count(check_ins.id) AS checkins"])
      .joins(people: :check_ins).where(check_ins: {item_id: @cur_cat.items}).group("services.id").order('count(check_ins.id) DESC')
    end
  end

  def get_pdf
    allCategories = Category.all

    pdf = CategoriesPdf.new(allCategories, view_context)
    send_data pdf.render, filename: 
    "Categories_List_#{Time.now.to_i}.pdf",
    type: "application/pdf"
    #disposition: inline #open in browser

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, sub_categories_attributes: [:id, :name, :description, :category_id, :_destroy])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="modal fade" id="<%=formid%>" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close create-form-close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">New Category!</h4>
        </div>


<%= form_for(ncategory, html: { multipart: true}, remote: true) do |f| %>

        <div class="modal-body">

          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>
          <br>
          <div class="field">
            <%= f.label :description %><br>
            <%= f.text_area :description %>
          </div>
          <br>

          <div id="subs-form<%=formid%>">
          
            <strong>SubCategories:</strong><br>

              <!--<button id="<%=formid%>" type="button" class="add-sub btn btn-default">Add a SubCategory</button>-->
            <fieldset>

              <%= f.fields_for :sub_categories do |subcat_form| %>
                <%= render partial: 'categories/sub_category_fields' , locals: { f: subcat_form } %>
              <% end %>

              <%= link_to_add_association "Add SubCategory", f, :sub_categories,class: "btn btn-default", :render_options => {:wrapper => 'bootstrap' } %>

            </fieldset>
          </div>
           

        </div>

        <div id="notice-location-form<%= ('-edit' + ncategory.id.to_s) unless newform  %>">
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default create-form-close" data-dismiss="modal" >Close</button>
          <%= f.submit(class: "btn btn-primary") %>
        </div>

<% end %>

</div>
    </div>
  </div>

app/views/categories/_list_table_categories.html.erb
<div id="create-form" linkto="<%=categories_close_new_modal_path%>">

  
  <div class="btn-group pull-right">
    <%= link_to "Download Categories List", categories_get_pdf_path, :class => "btn btn-default" %>
    <button class="btn btn-primary" data-toggle="modal" data-target="#category-form">Add New Category</button>
  </div>

  <%= render partial: 'categories/form' , locals: {ncategory: ncategory, formid: "category-form" , newform: true} %>

</div>

<br><br>

<div>
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th><%= sortable 'name','Name', categories_path %></th>
        <th>Description</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody id="mytable">
      <% categories.each do |category| %>
        <%= render partial: 'categories/record' , locals: {category: category} %>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/categories/_list_top_categories.html.erb
<% unless categories == nil %>

	<% categories.in_groups_of(4,false).each do |group| %>
		<div class="row">
			<% group.each do |category| %>
				<div class="col-sm-6 col-md-3">
				    <div class="thumbnail">
				    	<span class="badge"><%= category.checkins_count %> Check ins</span> 
				      <div class="caption">
				        <h3><%= category.name %></h3>
				        <%= label_tag 'Description:' %>
				        <p><%= category.description %></p>
				        <p>
				        	<%= label_tag 'Subcategories:' %>
				        	<p>
					        	<% SubCategory.where(category_id: category.id).each do |sub| %>
					        	<span class="label label-primary"><%= sub.name %></span>
					        	<% end %>
				        	</p>
				        </p>
				      </div>
				    </div>
			  	</div>
		  <% end %>
		</div>
	<% end %>
<% else %>

emptyyyyyy

<% end %>

app/views/categories/_mcategory.html.erb
<% unless cat == nil %>

	<div class="thumbnail">
			<div class="caption">
					        <h3><%= cat.name %></h3>
					        <%= label_tag 'Description:' %>
					        <p><%= cat.description %></p>
					       
				        	<%= label_tag 'SubCategories:' %>
				        	<div class="table-responsive">
							  <table class="table table-hover table-condensed">
							    <thead>
							      <tr>
							        <th>Name</th>
							        <th>Description</th>
							      </tr>
							    </thead>

							    <tbody id="mytable">
							      <% cat.sub_categories.each do |scat| %>
							        <%= render partial: 'sub_categories/record' , locals: {sub_category: scat} %>
							      <% end %>
							    </tbody>
							  </table>
							  <br>
							</div>
				        	
				<% unless serv.empty? %>
					<div>
						<strong>Services:</strong>
						<br>
						<ul class="list-group">
							<% serv.each do |s| %>
							  <li class="list-group-item"><%= s.name %>  <%= s.sub_name %>  <span class="badge"><%= s.checkins %> Points</span></li>
						 	<% end %>
						</ul>
					</div>
				<% end %>
			</div>
	</div>
	
<% end %>

app/views/categories/_record.html.erb
<tr id="record<%=category.id%>">
  <td><%= category.name %></td>
  <td><%= category.description %></td>

  <td>
    <%= render partial: 'categories/form' , locals: {ncategory: category, formid: "form-edit#{category.id}", newform: false} %>
    <button class="btn btn-info pull-right btn-block" data-toggle="modal" data-target="#form-edit<%=category.id%>">Edit</button>
  </td>

  <td>
  	<% if category.items.count == 0 %>
    <%= button_to 'Delete', category, remote: true, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-block" %>
    <% else %>
    <%= button_to "Cannot Delete, #{category.items.count} items linked", category, remote: true, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger disabled btn-block" %>
    <% end %>
  </td>
</tr>

app/views/categories/_sub_category_fields.html.erb
<fieldset>
    <div class="thumbnail">  
            <%= f.label :name %>
            <br>
            <%= f.text_field :name %>

            
            <br>
                 
            <%= f.label :description %>
            <br>
            <%= f.text_field :description %>

            <br>

            <%= f.check_box :_destroy ,class: "remove_fields"%>
            <%= f.label :destroy , "Remove SubCategory"%>

            <br>
    </div>
</fieldset>

app/views/categories/close_new_modal.js.erb
$("#create-form").empty();
$("#create-form").append("<div class='btn-group pull-right'><%= escape_javascript(link_to 'Download Categories List', categories_get_pdf_path, :class => 'btn btn-default') %><button class='btn btn-primary' data-toggle='modal' data-target='#category-form'>Add New Category</button></div>");
$("#create-form").append("<%= escape_javascript(render partial: 'categories/form' , locals: {ncategory: @ncategory, formid: 'category-form', newform: true})%>");

app/views/categories/create.js.erb
$("#notice-location-form").empty();
$("#notice-location-form").append("<div class='panel' id='notice'><div class='panel-heading' id='noticeh'></div></div>"); 
 
<% if @category == nil %>

	$("#noticeh").append("<div class='panel-title'>Failed: </div><ul id='noticeb'></ul>");

	<% @str.each do |s| %>
		$("#noticeb").append("<li><%= s %></li>");
	<% end %>
	
<% else %>

	$("#mytable").prepend("<%=escape_javascript(render partial: 'categories/record' , locals: {category: @category})%>");
	$("#noticeh").append("<%= @str %>");
	//window.location.reload();

<% end %>

$("#notice").addClass("<%= @alert %>");

app/views/categories/destroy.js.erb
$("#record<%=@catid%>").replaceWith("<div id='record<%=@catid%>' class='panel panel-danger'><div class='panel-heading'><div class='panel-title'>Deleting Category</div></div></div>");
$("#record<%=@catid%>").fadeOut(1000);

app/views/categories/get_category.js.erb
<% unless @cur_cat == nil %>
	$("#srchCatPos").html("<%= escape_javascript(render partial: 'categories/mcategory', locals: { cat:  @cur_cat, serv: @services } ) %>"); 
<% else %>
	$("#srchCatPos").empty(); 
<% end %>

app/views/categories/index.html.erb
<h1>Manage Categories</h1>

<div role="tabpanel" class="shadow-z-4" style="background-color:#ffffff;">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">

    <li role="presentation"  class="active">
      <a href="#crud" aria-controls="crud" role="tab" data-toggle="tab">Create & edit Categories</a>
    </li>

    <li role="presentation" >
      <a href="#srchitem" aria-controls="srchitem" role="tab" data-toggle="tab">Search for a Category</a>
    </li>

    <li role="presentation">
      <a href="#topc" aria-controls="topi" role="tab" data-toggle="tab">Top Categories</a>
    </li>

  </ul>

  <!-- Tab panes -->
  <div class="tab-content crud-content">

    <div role="tabpanel" class="tab-pane active" id="crud">
      <%= render partial: 'categories/list_table_categories' , locals: { categories: @categories, ncategory: @ncategory } %>
    </div>

    <div role="tabpanel" class="tab-pane" id="srchitem">

      <div class="form-group">

             <div class="input-group btn-group">

                <%= form_tag(categories_get_category_path, method: "get", remote: true, id: "crud-srch") do %>
                    
                    <div class="btn-group">
                      <div class="btn-group">
                          <%= text_field_tag(:catName, nil,class: "form-control", placeholder: "category name") %>
                      </div>
                      
                      <div class="btn-group">             
                          <%= submit_tag("Get category!",class: "btn btn-default")%>
                      </div>
                    
                    </div>

                <% end %>

              </div>
          </div>

      <div id="srchCatPos">
      </div>

    </div>

    <div role="tabpanel" class="tab-pane" id="topc">
      <%= render partial: 'categories/list_top_categories' , locals: { categories: @topCategories } %>
    </div>
    
  </div>

</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/update.js.erb
$("#notice-location-form-edit<%= @catid %>").empty();
$("#notice-location-form-edit<%= @catid %>").append("<div class='panel' id='notice<%= @catid %>'><div class='panel-heading' id='noticeh<%= @catid %>'></div></div>"); 
 
<% if @category == nil %>

	$("#noticeh<%= @catid %>").append("<div class='panel-title'>Failed: </div><ul id='noticeb<%= @catid %>'></ul>");

	<% @str.each do |s| %>
		$("#noticeb<%= @catid %>").append("<li><%= s %></li>");
	<% end %>
	
	$("#notice<%= @catid %>").addClass("<%= @alert %>");
<% else %>

	$("#record<%=@category.id%>").replaceWith("<%=escape_javascript(render partial: 'categories/record' , locals: {category: @category})%>");
	//$("#noticeh<%= @catid %>").append("<%= @str %>");

	$("#msgmodal").replaceWith("<%=escape_javascript(render partial: 'layouts/confirm' , locals: {str: @str})%>");
	$("#mymodal").modal("show");
<% end %>